<?php
function custom_weather_block_info() {
  $blocks = array();
  $blocks['custom_weather_block'] = array(
    'info' => t('Custom Weather Block'),
  );
  return $blocks;
}

/**
 * Implement hook_theme().
 */

function custom_weather_block_theme(): array {
  return [
    'custom_weather_block_template' => [
      'variables' => [
        'content' => NULL,
        'custom_weather_type' => NULL,
      ],
    ],
  ];
}
